package com.application.bean;
// Generated Feb 4, 2016 1:30:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AddressVerifiedByUserDetails generated by hbm2java
 */
@Entity
@Table(name="address_verified_by_user_details"
    ,catalog="android"
)
public class AddressVerifiedByUserDetails  implements java.io.Serializable {


     private Integer pk;
     private UserDetails userDetails;
     private UsersAddress usersAddress;
     private Date verifiedDate;
     private int trustScore;
     private Date updatedTime;
     private Date createdTime;

    public AddressVerifiedByUserDetails() {
    }

    public AddressVerifiedByUserDetails(UserDetails userDetails, UsersAddress usersAddress, Date verifiedDate, int trustScore, Date updatedTime, Date createdTime) {
       this.userDetails = userDetails;
       this.usersAddress = usersAddress;
       this.verifiedDate = verifiedDate;
       this.trustScore = trustScore;
       this.updatedTime = updatedTime;
       this.createdTime = createdTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_details_fk", nullable=false)
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_address_fk", nullable=false)
    public UsersAddress getUsersAddress() {
        return this.usersAddress;
    }
    
    public void setUsersAddress(UsersAddress usersAddress) {
        this.usersAddress = usersAddress;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="verified_date", nullable=false, length=19)
    public Date getVerifiedDate() {
        return this.verifiedDate;
    }
    
    public void setVerifiedDate(Date verifiedDate) {
        this.verifiedDate = verifiedDate;
    }

    
    @Column(name="trust_score", nullable=false)
    public int getTrustScore() {
        return this.trustScore;
    }
    
    public void setTrustScore(int trustScore) {
        this.trustScore = trustScore;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_time", nullable=false, length=19)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }




}


