package com.application.bean;
// Generated Feb 4, 2016 1:30:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AddressType generated by hbm2java
 */
@Entity
@Table(name="address_type"
    ,catalog="android"
)
public class AddressType  implements java.io.Serializable {


     private Integer pk;
     private String type;
     private String description;
     private boolean active;
     private Date createdTime;
     private Date updatedTime;
//     private Set usersAddresses = new HashSet(0);

    public AddressType() {
    }

	
    public AddressType(String type, String description, boolean active, Date createdTime, Date updatedTime) {
        this.type = type;
        this.description = description;
        this.active = active;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
    }
    public AddressType(String type, String description, boolean active, Date createdTime, Date updatedTime, Set usersAddresses) {
       this.type = type;
       this.description = description;
       this.active = active;
       this.createdTime = createdTime;
       this.updatedTime = updatedTime;
//       this.usersAddresses = usersAddresses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    
    @Column(name="type", nullable=false, length=300)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="description", nullable=false, length=300)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_time", nullable=false, length=19)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="addressType")
//    public Set getUsersAddresses() {
//        return this.usersAddresses;
//    }
//    
//    public void setUsersAddresses(Set usersAddresses) {
//        this.usersAddresses = usersAddresses;
//    }




}


