package com.application.bean;
// Generated Feb 4, 2016 1:30:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactType generated by hbm2java
 */
@Entity
@Table(name="contact_type"
    ,catalog="android"
)
public class ContactType  implements java.io.Serializable {


     private int pk;
     private String type;
     private String description;
     private boolean active;
     private Date createdTime;
     private Date updateTime;
//     private Set userContacts = new HashSet(0);

    public ContactType() {
    }

	
    public ContactType(int pk, String type, String description, boolean active, Date createdTime, Date updateTime) {
        this.pk = pk;
        this.type = type;
        this.description = description;
        this.active = active;
        this.createdTime = createdTime;
        this.updateTime = updateTime;
    }
    public ContactType(int pk, String type, String description, boolean active, Date createdTime, Date updateTime, Set userContacts) {
       this.pk = pk;
       this.type = type;
       this.description = description;
       this.active = active;
       this.createdTime = createdTime;
       this.updateTime = updateTime;
//       this.userContacts = userContacts;
    }
   
     @Id 

    
    @Column(name="pk", unique=true, nullable=false)
    public int getPk() {
        return this.pk;
    }
    
    public void setPk(int pk) {
        this.pk = pk;
    }

    
    @Column(name="type", nullable=false, length=300)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="description", nullable=false, length=300)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_time", nullable=false, length=19)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="contactType")
//    public Set getUserContacts() {
//        return this.userContacts;
//    }
//    
//    public void setUserContacts(Set userContacts) {
//        this.userContacts = userContacts;
//    }




}


