package com.application.bean;
// Generated Feb 4, 2016 1:30:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="android"
)
public class Users  implements java.io.Serializable {


     private Integer pk;
     private String userName;
     private String password;
     private Date createdTime;
     private Date updatedTime;
     private Date lastLogingTime;
     private Date lastActiveTime;
     private Boolean disabled;

    public Users() {
    }

	
    public Users(String userName, String password, Date createdTime, Date updatedTime, Date lastLogingTime, Date lastActiveTime) {
        this.userName = userName;
        this.password = password;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
        this.lastLogingTime = lastLogingTime;
        this.lastActiveTime = lastActiveTime;
    }
    public Users(String userName, String password, Date createdTime, Date updatedTime, Date lastLogingTime, Date lastActiveTime, Boolean disabled) {
       this.userName = userName;
       this.password = password;
       this.createdTime = createdTime;
       this.updatedTime = updatedTime;
       this.lastLogingTime = lastLogingTime;
       this.lastActiveTime = lastActiveTime;
       this.disabled = disabled;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    
    @Column(name="user_name", nullable=false, length=300)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false, length=300)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_time", nullable=false, length=19)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_loging_time", nullable=false, length=19)
    public Date getLastLogingTime() {
        return this.lastLogingTime;
    }
    
    public void setLastLogingTime(Date lastLogingTime) {
        this.lastLogingTime = lastLogingTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_active_time", nullable=false, length=19)
    public Date getLastActiveTime() {
        return this.lastActiveTime;
    }
    
    public void setLastActiveTime(Date lastActiveTime) {
        this.lastActiveTime = lastActiveTime;
    }

    
    @Column(name="disabled")
    public Boolean getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }




}


