package com.application.bean;
// Generated Feb 4, 2016 1:30:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsersAddress generated by hbm2java
 */
@Entity
@Table(name="users_address"
    ,catalog="android"
)
public class UsersAddress  implements java.io.Serializable {


     private Integer pk;
     private AddressType addressType;
     private UserDetails userDetails;
     private String addressLine1;
     private String addressLine2;
     private String street;
     private String district;
     private String state;
     private String country;
     private String pin;
     private String post;
     private String landMark;
     private String nearByPlace;
     private boolean active;
     private Date createdTime;
     private Date updateTime;
     private boolean addressVerified;
//     private Set addressVerifiedByUserDetailses = new HashSet(0);

    public UsersAddress() {
    }

	
    public UsersAddress(AddressType addressType, UserDetails userDetails, String addressLine1, String addressLine2, String street, String district, String state, String country, String pin, String post, String landMark, String nearByPlace, boolean active, Date createdTime, Date updateTime, boolean addressVerified) {
        this.addressType = addressType;
        this.userDetails = userDetails;
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.street = street;
        this.district = district;
        this.state = state;
        this.country = country;
        this.pin = pin;
        this.post = post;
        this.landMark = landMark;
        this.nearByPlace = nearByPlace;
        this.active = active;
        this.createdTime = createdTime;
        this.updateTime = updateTime;
        this.addressVerified = addressVerified;
    }
    public UsersAddress(AddressType addressType, UserDetails userDetails, String addressLine1, String addressLine2, String street, String district, String state, String country, String pin, String post, String landMark, String nearByPlace, boolean active, Date createdTime, Date updateTime, boolean addressVerified, Set addressVerifiedByUserDetailses) {
       this.addressType = addressType;
       this.userDetails = userDetails;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.street = street;
       this.district = district;
       this.state = state;
       this.country = country;
       this.pin = pin;
       this.post = post;
       this.landMark = landMark;
       this.nearByPlace = nearByPlace;
       this.active = active;
       this.createdTime = createdTime;
       this.updateTime = updateTime;
       this.addressVerified = addressVerified;
//       this.addressVerifiedByUserDetailses = addressVerifiedByUserDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="address_type_fk", nullable=false)
    public AddressType getAddressType() {
        return this.addressType;
    }
    
    public void setAddressType(AddressType addressType) {
        this.addressType = addressType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_details_fk", nullable=false)
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }

    
    @Column(name="address_line1", nullable=false, length=500)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="address_line2", nullable=false, length=500)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="street", nullable=false, length=200)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="district", nullable=false, length=200)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="state", nullable=false, length=200)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="country", nullable=false, length=200)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="pin", nullable=false, length=200)
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }

    
    @Column(name="post", nullable=false, length=300)
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }

    
    @Column(name="land_mark", nullable=false, length=300)
    public String getLandMark() {
        return this.landMark;
    }
    
    public void setLandMark(String landMark) {
        this.landMark = landMark;
    }

    
    @Column(name="near_by_place", nullable=false, length=300)
    public String getNearByPlace() {
        return this.nearByPlace;
    }
    
    public void setNearByPlace(String nearByPlace) {
        this.nearByPlace = nearByPlace;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_time", nullable=false, length=19)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    
    @Column(name="address_verified", nullable=false)
    public boolean isAddressVerified() {
        return this.addressVerified;
    }
    
    public void setAddressVerified(boolean addressVerified) {
        this.addressVerified = addressVerified;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="usersAddress")
//    public Set getAddressVerifiedByUserDetailses() {
//        return this.addressVerifiedByUserDetailses;
//    }
//    
//    public void setAddressVerifiedByUserDetailses(Set addressVerifiedByUserDetailses) {
//        this.addressVerifiedByUserDetailses = addressVerifiedByUserDetailses;
//    }




}


