package com.application.bean;
// Generated Feb 4, 2016 1:30:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name="user_details"
    ,catalog="android"
)
public class UserDetails  implements java.io.Serializable {


     private Integer pk;
     private UserLogin userLogin;
     private String firstName;
     private String lastName;
     private Date dateOfBirth;
     private String gender;
     private Date createdTime;
     private Date updatedTime;
//     private Set userContacts = new HashSet(0);
//     private Set usersAddresses = new HashSet(0);
//     private Set addressVerifiedByUserDetailses = new HashSet(0);

    public UserDetails() {
    }

	
    public UserDetails(UserLogin userLogin, String firstName, String lastName, Date dateOfBirth, String gender, Date createdTime, Date updatedTime) {
        this.userLogin = userLogin;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
    }
    public UserDetails(UserLogin userLogin, String firstName, String lastName, Date dateOfBirth, String gender, Date createdTime, Date updatedTime, Set userContacts, Set usersAddresses, Set addressVerifiedByUserDetailses) {
       this.userLogin = userLogin;
       this.firstName = firstName;
       this.lastName = lastName;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.createdTime = createdTime;
       this.updatedTime = updatedTime;
//       this.userContacts = userContacts;
//       this.usersAddresses = usersAddresses;
//       this.addressVerifiedByUserDetailses = addressVerifiedByUserDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_login_fk", nullable=false)
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }

    
    @Column(name="first_name", nullable=false, length=300)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=300)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_of_birth", nullable=false, length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="gender", nullable=false, length=300)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_time", nullable=false, length=19)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="userDetails")
//    public Set getUserContacts() {
//        return this.userContacts;
//    }
//    
//    public void setUserContacts(Set userContacts) {
//        this.userContacts = userContacts;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="userDetails")
//    public Set getUsersAddresses() {
//        return this.usersAddresses;
//    }
//    
//    public void setUsersAddresses(Set usersAddresses) {
//        this.usersAddresses = usersAddresses;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="userDetails")
//    public Set getAddressVerifiedByUserDetailses() {
//        return this.addressVerifiedByUserDetailses;
//    }
//    
//    public void setAddressVerifiedByUserDetailses(Set addressVerifiedByUserDetailses) {
//        this.addressVerifiedByUserDetailses = addressVerifiedByUserDetailses;
//    }




}


